/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VOvChart: typeof import('./src/components/data/VOvChart.vue')['default']
    VOvDialog: typeof import('./src/components/overlays/VOvDialog.vue')['default']
    VOvEditor: typeof import('./src/components/forms/VOvEditor.vue')['default']
    VOvForm: typeof import('./src/components/forms/VOvForm.vue')['default']
    VOvMap: typeof import('./src/components/content/VOvMap.vue')['default']
    VOvMedia: typeof import('./src/components/content/VOvMedia.vue')['default']
    VOvPad: typeof import('./src/components/forms/VOvPad.vue')['default']
    VOvShare: typeof import('./src/components/content/VOvShare.vue')['default']
    VOvTable: typeof import('./src/components/data/VOvTable.vue')['default']
    VOvView: typeof import('./src/components/data/VOvView.vue')['default']
  }
}
