/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VOvChart: typeof import('@odbvue/web/components')['VOvChart']
    VOvDialog: typeof import('@odbvue/web/components')['VOvDialog']
    VOvEditor: typeof import('@odbvue/web/components')['VOvEditor']
    VOvForm: typeof import('@odbvue/web/components')['VOvForm']
    VOvMap: typeof import('@odbvue/web/components')['VOvMap']
    VOvMedia: typeof import('@odbvue/web/components')['VOvMedia']
    VOvShare: typeof import('@odbvue/web/components')['VOvShare']
    VOvTable: typeof import('@odbvue/web/components')['VOvTable']
    VOvView: typeof import('@odbvue/web/components')['VOvView']
  }
}
