/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '//sandbox/': RouteRecordInfo<
      '//sandbox/',
      '/sandbox',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//sandbox/sandbox-chart': RouteRecordInfo<
      '//sandbox/sandbox-chart',
      '/sandbox/sandbox-chart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//sandbox/sandbox-dialog': RouteRecordInfo<
      '//sandbox/sandbox-dialog',
      '/sandbox/sandbox-dialog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//sandbox/sandbox-dnd': RouteRecordInfo<
      '//sandbox/sandbox-dnd',
      '/sandbox/sandbox-dnd',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//sandbox/sandbox-editor': RouteRecordInfo<
      '//sandbox/sandbox-editor',
      '/sandbox/sandbox-editor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//sandbox/sandbox-form': RouteRecordInfo<
      '//sandbox/sandbox-form',
      '/sandbox/sandbox-form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//sandbox/sandbox-http': RouteRecordInfo<
      '//sandbox/sandbox-http',
      '/sandbox/sandbox-http',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//sandbox/sandbox-map': RouteRecordInfo<
      '//sandbox/sandbox-map',
      '/sandbox/sandbox-map',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//sandbox/sandbox-media': RouteRecordInfo<
      '//sandbox/sandbox-media',
      '/sandbox/sandbox-media',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//sandbox/sandbox-pad': RouteRecordInfo<
      '//sandbox/sandbox-pad',
      '/sandbox/sandbox-pad',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//sandbox/sandbox-share': RouteRecordInfo<
      '//sandbox/sandbox-share',
      '/sandbox/sandbox-share',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//sandbox/sandbox-table': RouteRecordInfo<
      '//sandbox/sandbox-table',
      '/sandbox/sandbox-table',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//sandbox/sandbox-ui': RouteRecordInfo<
      '//sandbox/sandbox-ui',
      '/sandbox/sandbox-ui',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//sandbox/sandbox-view': RouteRecordInfo<
      '//sandbox/sandbox-view',
      '/sandbox/sandbox-view',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/modules/sandbox/pages/index.vue': {
      routes:
        | '//sandbox/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/sandbox-chart.vue': {
      routes:
        | '//sandbox/sandbox-chart'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/sandbox-dialog.vue': {
      routes:
        | '//sandbox/sandbox-dialog'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/sandbox-dnd.vue': {
      routes:
        | '//sandbox/sandbox-dnd'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/sandbox-editor.vue': {
      routes:
        | '//sandbox/sandbox-editor'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/sandbox-form.vue': {
      routes:
        | '//sandbox/sandbox-form'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/sandbox-http.vue': {
      routes:
        | '//sandbox/sandbox-http'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/sandbox-map.vue': {
      routes:
        | '//sandbox/sandbox-map'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/sandbox-media.vue': {
      routes:
        | '//sandbox/sandbox-media'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/sandbox-pad.vue': {
      routes:
        | '//sandbox/sandbox-pad'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/sandbox-share.vue': {
      routes:
        | '//sandbox/sandbox-share'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/sandbox-table.vue': {
      routes:
        | '//sandbox/sandbox-table'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/sandbox-ui.vue': {
      routes:
        | '//sandbox/sandbox-ui'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/sandbox-view.vue': {
      routes:
        | '//sandbox/sandbox-view'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/about.md': {
      routes:
        | '/about'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
