/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/': RouteRecordInfo<
      '/sandbox/',
      '/sandbox',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/capabilities/[capability]': RouteRecordInfo<
      '/sandbox/capabilities/[capability]',
      '/sandbox/capabilities/:capability',
      { capability: ParamValue<true> },
      { capability: ParamValue<false> },
      | never
    >,
    '/sandbox/capabilities/components': RouteRecordInfo<
      '/sandbox/capabilities/components',
      '/sandbox/capabilities/components',
      Record<never, never>,
      Record<never, never>,
      | '/sandbox/capabilities/components/chart'
      | '/sandbox/capabilities/components/dialog'
      | '/sandbox/capabilities/components/editor'
      | '/sandbox/capabilities/components/form'
      | '/sandbox/capabilities/components/map'
      | '/sandbox/capabilities/components/media'
      | '/sandbox/capabilities/components/pad'
      | '/sandbox/capabilities/components/share'
      | '/sandbox/capabilities/components/table'
      | '/sandbox/capabilities/components/view'
    >,
    '/sandbox/capabilities/components/chart': RouteRecordInfo<
      '/sandbox/capabilities/components/chart',
      '/sandbox/capabilities/components/chart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/capabilities/components/dialog': RouteRecordInfo<
      '/sandbox/capabilities/components/dialog',
      '/sandbox/capabilities/components/dialog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/capabilities/components/editor': RouteRecordInfo<
      '/sandbox/capabilities/components/editor',
      '/sandbox/capabilities/components/editor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/capabilities/components/form': RouteRecordInfo<
      '/sandbox/capabilities/components/form',
      '/sandbox/capabilities/components/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/capabilities/components/map': RouteRecordInfo<
      '/sandbox/capabilities/components/map',
      '/sandbox/capabilities/components/map',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/capabilities/components/media': RouteRecordInfo<
      '/sandbox/capabilities/components/media',
      '/sandbox/capabilities/components/media',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/capabilities/components/pad': RouteRecordInfo<
      '/sandbox/capabilities/components/pad',
      '/sandbox/capabilities/components/pad',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/capabilities/components/share': RouteRecordInfo<
      '/sandbox/capabilities/components/share',
      '/sandbox/capabilities/components/share',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/capabilities/components/table': RouteRecordInfo<
      '/sandbox/capabilities/components/table',
      '/sandbox/capabilities/components/table',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/capabilities/components/view': RouteRecordInfo<
      '/sandbox/capabilities/components/view',
      '/sandbox/capabilities/components/view',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/capabilities/errors': RouteRecordInfo<
      '/sandbox/capabilities/errors',
      '/sandbox/capabilities/errors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/capabilities/i18n': RouteRecordInfo<
      '/sandbox/capabilities/i18n',
      '/sandbox/capabilities/i18n',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/capabilities/routing': RouteRecordInfo<
      '/sandbox/capabilities/routing',
      '/sandbox/capabilities/routing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/capabilities/state': RouteRecordInfo<
      '/sandbox/capabilities/state',
      '/sandbox/capabilities/state',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/capabilities/ui': RouteRecordInfo<
      '/sandbox/capabilities/ui',
      '/sandbox/capabilities/ui',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/sandbox-dnd': RouteRecordInfo<
      '/sandbox/sandbox-dnd',
      '/sandbox/sandbox-dnd',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/sandbox-http': RouteRecordInfo<
      '/sandbox/sandbox-http',
      '/sandbox/sandbox-http',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/about.md': {
      routes:
        | '/about'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/index.vue': {
      routes:
        | '/sandbox/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/capabilities/[capability].vue': {
      routes:
        | '/sandbox/capabilities/[capability]'
      views:
        | never
      pathParamNames:
        | 'capability'
    }
    'src/modules/sandbox/pages/capabilities/components.vue': {
      routes:
        | '/sandbox/capabilities/components'
        | '/sandbox/capabilities/components/chart'
        | '/sandbox/capabilities/components/dialog'
        | '/sandbox/capabilities/components/editor'
        | '/sandbox/capabilities/components/form'
        | '/sandbox/capabilities/components/map'
        | '/sandbox/capabilities/components/media'
        | '/sandbox/capabilities/components/pad'
        | '/sandbox/capabilities/components/share'
        | '/sandbox/capabilities/components/table'
        | '/sandbox/capabilities/components/view'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/capabilities/components/chart.vue': {
      routes:
        | '/sandbox/capabilities/components/chart'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/capabilities/components/dialog.vue': {
      routes:
        | '/sandbox/capabilities/components/dialog'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/capabilities/components/editor.vue': {
      routes:
        | '/sandbox/capabilities/components/editor'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/capabilities/components/form.vue': {
      routes:
        | '/sandbox/capabilities/components/form'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/capabilities/components/map.vue': {
      routes:
        | '/sandbox/capabilities/components/map'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/capabilities/components/media.vue': {
      routes:
        | '/sandbox/capabilities/components/media'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/capabilities/components/pad.vue': {
      routes:
        | '/sandbox/capabilities/components/pad'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/capabilities/components/share.vue': {
      routes:
        | '/sandbox/capabilities/components/share'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/capabilities/components/table.vue': {
      routes:
        | '/sandbox/capabilities/components/table'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/capabilities/components/view.vue': {
      routes:
        | '/sandbox/capabilities/components/view'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/capabilities/errors.vue': {
      routes:
        | '/sandbox/capabilities/errors'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/capabilities/i18n.vue': {
      routes:
        | '/sandbox/capabilities/i18n'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/capabilities/routing.vue': {
      routes:
        | '/sandbox/capabilities/routing'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/capabilities/state.vue': {
      routes:
        | '/sandbox/capabilities/state'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/capabilities/ui.vue': {
      routes:
        | '/sandbox/capabilities/ui'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/sandbox-dnd.vue': {
      routes:
        | '/sandbox/sandbox-dnd'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/modules/sandbox/pages/sandbox-http.vue': {
      routes:
        | '/sandbox/sandbox-http'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
