import { promises as fs } from 'node:fs'
import path from 'node:path'
import type { Plugin, ResolvedConfig } from 'vite'
import * as mdi from '@mdi/js'

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function generateContent(icons: string[]): string {
  const header =
    `/* eslint-disable */\n` +
    `/* prettier-ignore */\n` +
    `// @ts-nocheck\n` +
    `// noinspection JSUnusedGlobalSymbols\n` +
    `// Generated by vite-plugin-auto-import-mdi-icons\n\n`

  if (!icons.length) {
    return `${header}export default {}\n`
  }

  return (
    header +
    `import {\n\t${icons.join(',\n\t')}\n} from '@mdi/js'\n\n` +
    `export default {\n\t${icons.join(',\n\t')}\n}\n`
  )
}

type AutoImportMdiIconsOptions = {
  dirs?: string[]
  exts?: string[]
  pattern?: string
  outputPath?: string
  outputFile?: string
  log?: boolean
  failOnMissing?: boolean
}

export function AutoImportMdiIcons(options: AutoImportMdiIconsOptions = {}): Plugin {
  let config: ResolvedConfig

  const dirs = options.dirs ?? ['./src']
  const exts = options.exts ?? ['.vue', '.ts', '.md']
  const pattern = options.pattern ?? '$mdi'
  const outputPath = options.outputPath ?? './src/themes/'
  const outputFile = options.outputFile ?? 'icons.ts'
  const log = options.log ?? true
  const failOnMissing = options.failOnMissing ?? false

  const availableIcons = new Set(Object.keys(mdi))

  function logger(message: string): void {
    if (!log) return
    console.log(`\x1b[36m[Auto Import MDI Icons]\x1b[0m ${message}`)
  }

  function getOutputFilePath(): string {
    return path.resolve(config.root, outputPath, outputFile)
  }

  function isInsideDir(filePath: string, dir: string): boolean {
    const absoluteDir = path.resolve(config.root, dir)
    const relative = path.relative(absoluteDir, filePath)

    return Boolean(relative) && !relative.startsWith('..') && !path.isAbsolute(relative)
  }

  function shouldScanFile(filePath: string): boolean {
    if (!exts.includes(path.extname(filePath))) return false
    if (path.resolve(filePath) === getOutputFilePath()) return false

    return dirs.some((dir) => isInsideDir(filePath, dir))
  }

  function extractIcons(content: string): string[] {
    const regex = new RegExp(`${escapeRegex(pattern)}[A-Z][A-Za-z0-9]*`, 'g')

    return [...new Set(content.match(regex) ?? [])]
      .map((icon) => pattern.replace(/^\$/, '') + icon.slice(pattern.length))
      .toSorted()
  }

  async function collectIconsFromFile(filePath: string): Promise<string[]> {
    if (!shouldScanFile(filePath)) return []

    const content = await fs.readFile(filePath, 'utf-8')
    return extractIcons(content)
  }

  async function walkDir(dir: string): Promise<string[]> {
    const files: string[] = []

    let entries
    try {
      entries = await fs.readdir(dir, { withFileTypes: true })
    } catch {
      return files
    }

    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name)

      if (entry.isDirectory()) {
        files.push(...(await walkDir(fullPath)))
      } else if (entry.isFile() && shouldScanFile(fullPath)) {
        files.push(fullPath)
      }
    }

    return files
  }

  async function collectAllIcons(): Promise<string[]> {
    const icons = new Set<string>()

    for (const dir of dirs) {
      const absoluteDir = path.resolve(config.root, dir)
      const files = await walkDir(absoluteDir)

      for (const file of files) {
        for (const icon of await collectIconsFromFile(file)) {
          icons.add(icon)
        }
      }
    }

    return [...icons].toSorted()
  }

  function validateIcons(
    icons: string[],
    pluginContext: { warn(message: string): void; error(message: string): never },
  ) {
    const missing = icons.filter((icon) => !availableIcons.has(icon))

    if (!missing.length) return icons

    const message = `Unknown MDI icons: ${missing.join(', ')}`

    if (failOnMissing) {
      pluginContext.error(message)
    } else {
      pluginContext.warn(message)
    }

    return icons.filter((icon) => availableIcons.has(icon))
  }

  async function writeIfChanged(filePath: string, content: string): Promise<void> {
    await fs.mkdir(path.dirname(filePath), { recursive: true })

    let existing = ''
    try {
      existing = await fs.readFile(filePath, 'utf-8')
    } catch {
      // File does not exist yet.
    }

    if (existing === content) return

    await fs.writeFile(filePath, content)
    logger(`updated ${path.relative(config.root, filePath)}`)
  }

  async function regenerate(pluginContext: {
    warn(message: string): void
    error(message: string): never
  }) {
    const output = getOutputFilePath()
    const icons = await collectAllIcons()
    const validIcons = validateIcons(icons, pluginContext)
    const content = generateContent(validIcons)

    await writeIfChanged(output, content)
  }

  return {
    name: 'auto-import-mdi-icons',

    configResolved(resolvedConfig) {
      config = resolvedConfig
    },

    async buildStart() {
      await regenerate(this)
    },

    async handleHotUpdate() {
      await regenerate(this)
    },
  }
}
