/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by vite-plugin-auto-import-mdi-icons

import {
	mdiChartLine,
	mdiCog,
	mdiDotsVertical,
	mdiEarth,
	mdiEyePlusOutline,
	mdiFormatBold,
	mdiFormatHeader1,
	mdiFormatHeader2,
	mdiFormatHeader3,
	mdiFormatItalic,
	mdiFormatListBulleted,
	mdiFormatListNumbered,
	mdiFormatStrikethrough,
	mdiFormatUnderline,
	mdiGithub,
	mdiHeart,
	mdiHome,
	mdiInformation,
	mdiMenuLeft,
	mdiMinus,
	mdiPen,
	mdiTranslate,
	mdiWeatherNight,
	mdiWeatherSunny
} from "@mdi/js"

export default {
  mdiChartLine,
  mdiCog,
  mdiDotsVertical,
  mdiEarth,
  mdiEyePlusOutline,
  mdiFormatBold,
  mdiFormatHeader1,
  mdiFormatHeader2,
  mdiFormatHeader3,
  mdiFormatItalic,
  mdiFormatListBulleted,
  mdiFormatListNumbered,
  mdiFormatStrikethrough,
  mdiFormatUnderline,
  mdiGithub,
  mdiHeart,
  mdiHome,
  mdiInformation,
  mdiMenuLeft,
  mdiMinus,
  mdiPen,
  mdiTranslate,
  mdiWeatherNight,
  mdiWeatherSunny,
}
