/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by vite-plugin-auto-import-mdi-icons

import {
	mdiHeart,
	mdiHome,
	mdiInformation
} from "@mdi/js"

export default {
  mdiHeart,
  mdiHome,
  mdiInformation,
}
