CREATE TABLE odbvue.crm_discovery_requests (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE,
    name         VARCHAR2(200 CHAR),
    organization VARCHAR2(200 CHAR),
    phone        VARCHAR2(200 CHAR),
    email        VARCHAR2(200 CHAR) NOT NULL ENABLE,
    message      CLOB,
    created      TIMESTAMP(6) DEFAULT systimestamp NOT NULL ENABLE
);

ALTER TABLE odbvue.crm_discovery_requests ADD PRIMARY KEY ( id )
    USING INDEX ENABLE;


-- sqlcl_snapshot {"hash":"d6bda8cf3210a156ac44bc5b4b2d8eb6df4fe4f8","type":"TABLE","name":"CRM_DISCOVERY_REQUESTS","schemaName":"ODBVUE","sxml":"\n  <TABLE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>ODBVUE</SCHEMA>\n   <NAME>CRM_DISCOVERY_REQUESTS</NAME>\n   <RELATIONAL_TABLE>\n      <COL_LIST>\n         <COL_LIST_ITEM>\n            <NAME>ID</NAME>\n            <DATATYPE>NUMBER</DATATYPE>\n            <IDENTITY_COLUMN>\n               <SCHEMA>ODBVUE</SCHEMA>\n               \n            <DEFAULT>SYSTIMESTAMP</DEFAULT>\n            <NOT_NULL></NOT_NULL>\n         </COL_LIST_ITEM>\n      </COL_LIST>\n      <PRIMARY_KEY_CONSTRAINT_LIST>\n         <PRIMARY_KEY_CONSTRAINT_LIST_ITEM>\n            <COL_LIST>\n               <COL_LIST_ITEM>\n                  <NAME>ID</NAME>\n               </COL_LIST_ITEM>\n            </COL_LIST>\n            <USING_INDEX></USING_INDEX>\n         </PRIMARY_KEY_CONSTRAINT_LIST_ITEM>\n      </PRIMARY_KEY_CONSTRAINT_LIST>\n      <DEFAULT_COLLATION>USING_NLS_COMP</DEFAULT_COLLATION>\n      <PHYSICAL_PROPERTIES>\n         <HEAP_TABLE></HEAP_TABLE>\n      </PHYSICAL_PROPERTIES>\n   </RELATIONAL_TABLE>\n</TABLE>"}