/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by vite-plugin-auto-import-mdi-icons

import {
	mdiCog,
	mdiGithub,
	mdiHome,
	mdiInformation,
	mdiMinus
} from '@mdi/js'

export default {
	mdiCog,
	mdiGithub,
	mdiHome,
	mdiInformation,
	mdiMinus
}
