/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by vite-plugin-auto-import-mdi-icons

import {
	mdiChevronRight,
	mdiCog,
	mdiDotsVertical,
	mdiEyePlusOutline,
	mdiFlask,
	mdiGithub,
	mdiHome,
	mdiInformation,
	mdiMenuLeft,
	mdiMinus,
	mdiWeatherNight,
	mdiWeatherSunny
} from '@mdi/js'

export default {
	mdiChevronRight,
	mdiCog,
	mdiDotsVertical,
	mdiEyePlusOutline,
	mdiFlask,
	mdiGithub,
	mdiHome,
	mdiInformation,
	mdiMenuLeft,
	mdiMinus,
	mdiWeatherNight,
	mdiWeatherSunny
}
