/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by vite-plugin-auto-import-mdi-icons

import {
	mdiHome
} from '@mdi/js'

export default {
	mdiHome
}
