import {
  OrdsEndpoint,
  type OrdsEndpointNode,
  type OrdsParamNode,
  type OrdsParamType,
} from './ords.js'

/** A value convertible to an ORDS endpoint node: an OrdsEndpoint or a plain node. */
type EndpointLike = OrdsEndpointNode | OrdsEndpoint

export type OrdsClientOptions = {
  /** Banner comment placed at the top of the generated file. */
  banner?: string
}

export type OrdsClientModules = {
  files: Map<string, string>
  index: string
}

function toNode(endpoint: EndpointLike): OrdsEndpointNode {
  return endpoint instanceof OrdsEndpoint ? endpoint.toNode() : endpoint
}

/** Map an ORDS parameter type to the nearest TypeScript type for a JSON client. */
export function ordsTypeToTsType(type: OrdsParamType): string {
  switch (type) {
    case 'INT':
    case 'DOUBLE':
    case 'LONG':
      return 'number'
    case 'BOOLEAN':
      return 'boolean'
    case 'RESULTSET':
      return 'unknown[]'
    case 'STRING':
    case 'TIMESTAMP':
      return 'string'
  }
}

function words(name: string): string[] {
  return name.split(/[-_\s]+/).filter(Boolean)
}

function toPascalCase(name: string): string {
  return words(name)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('')
}

function toCamelCase(name: string): string {
  const pascal = toPascalCase(name)
  return pascal.charAt(0).toLowerCase() + pascal.slice(1)
}

/** Full ORDS route for an endpoint: module base path joined with the template pattern. */
function routePath(node: OrdsEndpointNode): string {
  const base = node.basePath.replace(/\/+$/, '')
  const pattern = node.pattern.replace(/^\/+/, '')
  return base ? `${base}/${pattern}` : pattern
}

function operationBaseName(node: OrdsEndpointNode): string {
  return `${node.module}_${node.procedureName}`
}

function moduleFileName(module: string): string {
  return module
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

type Field = { name: string; type: string }

function resultColumnType(column: NonNullable<OrdsParamNode['resultColumns']>[number]): string {
  let type: string
  switch (column.type) {
    case 'number':
      type = 'number'
      break
    case 'boolean':
      type = 'boolean'
      break
    case 'string':
    case 'guid':
    case 'date':
    case 'timestamp':
    case 'clob':
      type = 'string'
      break
  }
  return column.nullable ? `${type} | null` : type
}

function requestFields(params: OrdsParamNode[]): Field[] {
  return params
    .filter((p) => p.direction === 'IN' || p.direction === 'IN OUT')
    .map((p) => ({ name: toCamelCase(p.name), type: ordsTypeToTsType(p.paramType) }))
}

function responseFields(params: OrdsParamNode[], operationName: string): Field[] {
  return params
    .filter((p) => p.direction === 'OUT' || p.direction === 'IN OUT')
    .map((p) => ({
      name: toCamelCase(p.name),
      type: p.resultColumns?.length
        ? `${operationName}${toPascalCase(p.name)}Item[]`
        : ordsTypeToTsType(p.paramType),
    }))
}

function emitShape(typeName: string, fields: Field[]): string {
  if (fields.length === 0) return `export type ${typeName} = Record<string, never>`
  const body = fields.map((f) => `  ${f.name}: ${f.type}`).join('\n')
  return `export interface ${typeName} {\n${body}\n}`
}

/**
 * Generate a typed ORDS client surface for the given endpoints:
 * per-operation request/response types, an `OrdsOperations` type map keyed by
 * operation id, and an `ordsOperations` descriptor map carrying method + path.
 */
export function generateOrdsClient(
  endpoints: EndpointLike[],
  options: OrdsClientOptions = {},
): string {
  const banner = options.banner ?? '// AUTO-GENERATED by `ov dt`. Do not edit by hand.'
  const nodes = endpoints.map(toNode)

  const shapes: string[] = []
  const typeMapEntries: string[] = []
  const descriptorEntries: string[] = []

  for (const node of nodes) {
    const baseName = operationBaseName(node)
    const id = toCamelCase(baseName)
    const pascal = toPascalCase(baseName)
    const requestType = `${pascal}Request`
    const responseType = `${pascal}Response`

    for (const param of node.params) {
      if (!param.resultColumns?.length) continue
      const itemType = `${pascal}${toPascalCase(param.name)}Item`
      shapes.push(
        emitShape(
          itemType,
          param.resultColumns.map((column) => ({
            name: toCamelCase(column.name),
            type: resultColumnType(column),
          })),
        ),
      )
    }

    shapes.push(emitShape(requestType, requestFields(node.params)))
    shapes.push(emitShape(responseType, responseFields(node.params, pascal)))

    typeMapEntries.push(`  ${id}: { request: ${requestType}; response: ${responseType} }`)
    descriptorEntries.push(`  ${id}: { method: '${node.method}', path: '${routePath(node)}' },`)
  }

  return [
    banner,
    '',
    "export type OrdsHttpMethod = 'GET' | 'POST' | 'PUT' | 'DELETE'",
    '',
    'export interface OrdsOperationDescriptor {',
    '  method: OrdsHttpMethod',
    '  path: string',
    '}',
    '',
    ...shapes.flatMap((shape) => [shape, '']),
    'export interface OrdsOperations {',
    ...typeMapEntries,
    '}',
    '',
    'export const ordsOperations = {',
    ...descriptorEntries,
    '} as const satisfies Record<keyof OrdsOperations, OrdsOperationDescriptor>',
    '',
  ].join('\n')
}

/** Generate one typed client file per ORDS module and an index namespace barrel. */
export function generateOrdsClientModules(
  endpoints: EndpointLike[],
  options: OrdsClientOptions = {},
): OrdsClientModules {
  const grouped = new Map<string, OrdsEndpointNode[]>()
  for (const endpoint of endpoints) {
    const node = toNode(endpoint)
    const group = grouped.get(node.module) ?? []
    group.push(node)
    grouped.set(node.module, group)
  }

  const files = new Map<string, string>()
  const exports: string[] = []
  for (const [module, nodes] of [...grouped.entries()].toSorted(([left], [right]) =>
    left.localeCompare(right),
  )) {
    const fileName = moduleFileName(module)
    if (!fileName || files.has(`${fileName}.ts`)) {
      throw new Error(`ORDS modules must map to unique file names: ${module}`)
    }
    files.set(`${fileName}.ts`, generateOrdsClient(nodes, options))
    exports.push(`export * as ${toCamelCase(module)} from './${fileName}.js'`)
  }

  const banner = options.banner ?? '// AUTO-GENERATED by `ov dt`. Do not edit by hand.'
  return {
    files,
    index: [banner, '', ...exports, ''].join('\n'),
  }
}
