import {
  OrdsEndpoint,
  type OrdsEndpointNode,
  type OrdsParamNode,
  type OrdsParamType,
} from './ords.js'

/** A value convertible to an ORDS endpoint node: an OrdsEndpoint or a plain node. */
type EndpointLike = OrdsEndpointNode | OrdsEndpoint

export type OrdsClientOptions = {
  /** Banner comment placed at the top of the generated file. */
  banner?: string
}

function toNode(endpoint: EndpointLike): OrdsEndpointNode {
  return endpoint instanceof OrdsEndpoint ? endpoint.toNode() : endpoint
}

/** Map an ORDS parameter type to the nearest TypeScript type for a JSON client. */
export function ordsTypeToTsType(type: OrdsParamType): string {
  switch (type) {
    case 'INT':
    case 'DOUBLE':
    case 'LONG':
      return 'number'
    case 'BOOLEAN':
      return 'boolean'
    case 'RESULTSET':
      return 'unknown[]'
    case 'STRING':
    case 'TIMESTAMP':
      return 'string'
  }
}

function words(name: string): string[] {
  return name.split(/[-_\s]+/).filter(Boolean)
}

function toPascalCase(name: string): string {
  return words(name)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('')
}

function toCamelCase(name: string): string {
  const pascal = toPascalCase(name)
  return pascal.charAt(0).toLowerCase() + pascal.slice(1)
}

/** Full ORDS route for an endpoint: module base path joined with the template pattern. */
function routePath(node: OrdsEndpointNode): string {
  const base = node.basePath.replace(/\/+$/, '')
  const pattern = node.pattern.replace(/^\/+/, '')
  return base ? `${base}/${pattern}` : pattern
}

function operationBaseName(node: OrdsEndpointNode): string {
  return `${node.module}_${node.procedureName}`
}

type Field = { name: string; type: string }

function requestFields(params: OrdsParamNode[]): Field[] {
  return params
    .filter((p) => p.direction === 'IN' || p.direction === 'IN OUT')
    .map((p) => ({ name: toCamelCase(p.name), type: ordsTypeToTsType(p.paramType) }))
}

function responseFields(params: OrdsParamNode[]): Field[] {
  return params
    .filter((p) => p.direction === 'OUT' || p.direction === 'IN OUT')
    .map((p) => ({ name: toCamelCase(p.name), type: ordsTypeToTsType(p.paramType) }))
}

function emitShape(typeName: string, fields: Field[]): string {
  if (fields.length === 0) return `export type ${typeName} = Record<string, never>`
  const body = fields.map((f) => `  ${f.name}: ${f.type}`).join('\n')
  return `export interface ${typeName} {\n${body}\n}`
}

/**
 * Generate a typed ORDS client surface for the given endpoints:
 * per-operation request/response types, an `OrdsOperations` type map keyed by
 * operation id, and an `ordsOperations` descriptor map carrying method + path.
 */
export function generateOrdsClient(
  endpoints: EndpointLike[],
  options: OrdsClientOptions = {},
): string {
  const banner = options.banner ?? '// AUTO-GENERATED by `ov dt`. Do not edit by hand.'
  const nodes = endpoints.map(toNode)

  const shapes: string[] = []
  const typeMapEntries: string[] = []
  const descriptorEntries: string[] = []

  for (const node of nodes) {
    const baseName = operationBaseName(node)
    const id = toCamelCase(baseName)
    const pascal = toPascalCase(baseName)
    const requestType = `${pascal}Request`
    const responseType = `${pascal}Response`

    shapes.push(emitShape(requestType, requestFields(node.params)))
    shapes.push(emitShape(responseType, responseFields(node.params)))

    typeMapEntries.push(`  ${id}: { request: ${requestType}; response: ${responseType} }`)
    descriptorEntries.push(`  ${id}: { method: '${node.method}', path: '${routePath(node)}' },`)
  }

  return [
    banner,
    '',
    "export type OrdsHttpMethod = 'GET' | 'POST' | 'PUT' | 'DELETE'",
    '',
    'export interface OrdsOperationDescriptor {',
    '  method: OrdsHttpMethod',
    '  path: string',
    '}',
    '',
    ...shapes.flatMap((shape) => [shape, '']),
    'export interface OrdsOperations {',
    ...typeMapEntries,
    '}',
    '',
    'export const ordsOperations = {',
    ...descriptorEntries,
    '} as const satisfies Record<keyof OrdsOperations, OrdsOperationDescriptor>',
    '',
  ].join('\n')
}
