// AUTO-GENERATED by `ov dt`. Do not edit by hand.

export type OrdsHttpMethod = 'GET' | 'POST' | 'PUT' | 'DELETE'

export interface OrdsOperationDescriptor {
  method: OrdsHttpMethod
  path: string
}

export type AppMeRequest = Record<string, never>

export interface AppMeResponse {
  version: string
  versionBase64: string
}

export interface OrdsOperations {
  appMe: { request: AppMeRequest; response: AppMeResponse }
}

export const ordsOperations = {
  appMe: { method: 'GET', path: 'app/auth/me' },
} as const satisfies Record<keyof OrdsOperations, OrdsOperationDescriptor>
