-- Table: ODBVUE.APP_USERS
-- Generated: 2026-01-16 12:45:43
-- Idempotent DDL - safe to run multiple times

-- Create table: APP_USERS
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM all_tables WHERE owner = 'ODBVUE' AND table_name = 'APP_USERS';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
CREATE TABLE ODBVUE.APP_USERS (
            ID NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL
           ,UUID RAW(16) DEFAULT SYS_GUID()  NOT NULL
           ,USERNAME VARCHAR2(203 CHAR) NOT NULL
           ,FULLNAME VARCHAR2(200 CHAR) NOT NULL
           ,CREATED TIMESTAMP(6) DEFAULT SYSTIMESTAMP  NOT NULL
           ,UPDATED TIMESTAMP(6)
           ,CONSTRAINT PK_APP_USERS PRIMARY KEY (ID)
        )';
    END IF;
END;
/

DECLARE
    v_exists NUMBER;
BEGIN
    -- Check if unique constraint on these columns already exists
    SELECT COUNT(*) INTO v_exists FROM all_constraints ac
    WHERE ac.owner = 'ODBVUE'
      AND ac.table_name = 'APP_USERS'
      AND ac.constraint_type IN ('U', 'P')
      AND (SELECT LISTAGG(acc.column_name, ',') WITHIN GROUP (ORDER BY acc.position)
           FROM all_cons_columns acc WHERE acc.owner = ac.owner AND acc.constraint_name = ac.constraint_name) = 'UUID';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ODBVUE.APP_USERS ADD CONSTRAINT UQ_APP_USERS_1 UNIQUE (UUID)';
    END IF;
END;
/

DECLARE
    v_exists NUMBER;
BEGIN
    -- Check if unique constraint on these columns already exists
    SELECT COUNT(*) INTO v_exists FROM all_constraints ac
    WHERE ac.owner = 'ODBVUE'
      AND ac.table_name = 'APP_USERS'
      AND ac.constraint_type IN ('U', 'P')
      AND (SELECT LISTAGG(acc.column_name, ',') WITHIN GROUP (ORDER BY acc.position)
           FROM all_cons_columns acc WHERE acc.owner = ac.owner AND acc.constraint_name = ac.constraint_name) = 'USERNAME';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ODBVUE.APP_USERS ADD CONSTRAINT UQ_APP_USERS_2 UNIQUE (USERNAME)';
    END IF;
END;
/
