import { promises as fs } from 'node:fs'
import path from 'node:path'
import type { Plugin, ResolvedConfig } from 'vite'
import * as mdi from '@mdi/js'

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function generateContent(icons: string[]): string {
  const header =
    `/* eslint-disable */\n` +
    `/* prettier-ignore */\n` +
    `// @ts-nocheck\n` +
    `// noinspection JSUnusedGlobalSymbols\n` +
    `// Generated by @odbvue/web/vite\n\n`

  if (!icons.length) return `${header}export default {}\n`

  return (
    header +
    `import {\n\t${icons.join(',\n\t')}\n} from '@mdi/js'\n\n` +
    `export default {\n\t${icons.join(',\n\t')}\n}\n`
  )
}

export type AutoImportMdiIconsOptions = {
  dirs?: string[]
  exts?: string[]
  pattern?: string
  outputPath?: string
  outputFile?: string
  log?: boolean
  failOnMissing?: boolean
}

/** Generates an application icon-alias module from `$mdi*` usages. */
export function autoImportMdiIcons(options: AutoImportMdiIconsOptions = {}): Plugin {
  let config: ResolvedConfig

  const dirs = options.dirs ?? ['./src']
  const exts = options.exts ?? ['.vue', '.ts', '.md']
  const pattern = options.pattern ?? '$mdi'
  const outputPath = options.outputPath ?? './src/themes/'
  const outputFile = options.outputFile ?? 'icons.ts'
  const log = options.log ?? true
  const failOnMissing = options.failOnMissing ?? false
  const availableIcons = new Set(Object.keys(mdi))

  function logger(message: string): void {
    if (log) console.log(`\x1b[36m[OdbVue MDI icons]\x1b[0m ${message}`)
  }

  function outputFilePath(): string {
    return path.resolve(config.root, outputPath, outputFile)
  }

  function isInsideDir(filePath: string, dir: string): boolean {
    const relative = path.relative(path.resolve(config.root, dir), filePath)
    return Boolean(relative) && !relative.startsWith('..') && !path.isAbsolute(relative)
  }

  function shouldScanFile(filePath: string): boolean {
    return (
      exts.includes(path.extname(filePath)) &&
      path.resolve(filePath) !== outputFilePath() &&
      dirs.some((dir) => isInsideDir(filePath, dir))
    )
  }

  function extractIcons(content: string): string[] {
    const regex = new RegExp(`${escapeRegex(pattern)}[A-Z][A-Za-z0-9]*`, 'g')
    return [...new Set(content.match(regex) ?? [])]
      .map((icon) => pattern.replace(/^\$/, '') + icon.slice(pattern.length))
      .toSorted()
  }

  async function walkDir(dir: string): Promise<string[]> {
    try {
      const entries = await fs.readdir(dir, { withFileTypes: true })
      const nested = await Promise.all(
        entries.map(async (entry) => {
          const fullPath = path.join(dir, entry.name)
          if (entry.isDirectory()) return walkDir(fullPath)
          return entry.isFile() && shouldScanFile(fullPath) ? [fullPath] : []
        }),
      )
      return nested.flat()
    } catch {
      return []
    }
  }

  async function collectIcons(): Promise<string[]> {
    const icons = new Set<string>()
    for (const dir of dirs) {
      for (const filePath of await walkDir(path.resolve(config.root, dir))) {
        const content = await fs.readFile(filePath, 'utf-8')
        for (const icon of extractIcons(content)) icons.add(icon)
      }
    }
    return [...icons].toSorted()
  }

  async function regenerate(pluginContext: {
    warn(message: string): void
    error(message: string): never
  }) {
    const icons = await collectIcons()
    const missing = icons.filter((icon) => !availableIcons.has(icon))
    if (missing.length) {
      const message = `Unknown MDI icons: ${missing.join(', ')}`
      if (failOnMissing) pluginContext.error(message)
      else pluginContext.warn(message)
    }

    const content = generateContent(icons.filter((icon) => availableIcons.has(icon)))
    const filePath = outputFilePath()
    await fs.mkdir(path.dirname(filePath), { recursive: true })

    let existing = ''
    try {
      existing = await fs.readFile(filePath, 'utf-8')
    } catch {
      // The generated module does not exist yet.
    }

    if (existing === content) return
    await fs.writeFile(filePath, content)
    logger(`updated ${path.relative(config.root, filePath)}`)
  }

  return {
    name: 'odbvue:auto-import-mdi-icons',
    configResolved(resolvedConfig) {
      config = resolvedConfig
    },
    async buildStart() {
      await regenerate(this)
    },
    async handleHotUpdate() {
      await regenerate(this)
    },
  }
}
