CREATE TABLE odbvue.app_users (
    id            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid           RAW(16) DEFAULT SYS_GUID() NOT NULL UNIQUE ,
    username              VARCHAR2(200 CHAR) NOT NULL UNIQUE,
    fullname      VARCHAR2(200 CHAR) NOT NULL,
    created         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated         TIMESTAMP 
);
