-- Schema: ODBVUE
-- Generated: 2026-01-16 12:24:40
-- Idempotent DDL - safe to run multiple times

-- Table: CRM_PERSONS
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM all_tables WHERE owner = 'ODBVUE' AND table_name = 'CRM_PERSONS';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
CREATE TABLE ODBVUE.CRM_PERSONS (
            ID NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL
           ,GUID RAW(16) DEFAULT SYS_GUID()  NOT NULL
           ,TYPE CHAR(1 CHAR) NOT NULL
           ,FIRST_NAME VARCHAR2(200 CHAR)
           ,LAST_NAME VARCHAR2(200 CHAR)
           ,LEGAL_NAME VARCHAR2(2000 CHAR)
           ,STATUS CHAR(1 CHAR) DEFAULT ''A'' NOT NULL
           ,ATTRIBUTES CLOB
           ,CREATED TIMESTAMP(6) DEFAULT SYSTIMESTAMP  NOT NULL
           ,MODIFIED TIMESTAMP(6) DEFAULT SYSTIMESTAMP 
           ,CONSTRAINT PK_CRM_PERSONS PRIMARY KEY (ID)
        )';
    END IF;
END;
/

-- Table: APP_USERS
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM all_tables WHERE owner = 'ODBVUE' AND table_name = 'APP_USERS';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
CREATE TABLE ODBVUE.APP_USERS (
            ID NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL
           ,UUID RAW(16) DEFAULT SYS_GUID()  NOT NULL
           ,USERNAME VARCHAR2(203 CHAR) NOT NULL
           ,FULLNAME VARCHAR2(200 CHAR) NOT NULL
           ,CREATED TIMESTAMP(6) DEFAULT SYSTIMESTAMP  NOT NULL
           ,UPDATED TIMESTAMP(6)
           ,CONSTRAINT PK_APP_USERS PRIMARY KEY (ID)
        )';
    END IF;
END;
/

DECLARE
    v_exists NUMBER;
BEGIN
    -- Check if unique constraint on these columns already exists
    SELECT COUNT(*) INTO v_exists FROM all_constraints ac
    WHERE ac.owner = 'ODBVUE'
      AND ac.table_name = 'CRM_PERSONS'
      AND ac.constraint_type IN ('U', 'P')
      AND (SELECT LISTAGG(acc.column_name, ',') WITHIN GROUP (ORDER BY acc.position)
           FROM all_cons_columns acc WHERE acc.owner = ac.owner AND acc.constraint_name = ac.constraint_name) = 'guid';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ODBVUE.CRM_PERSONS ADD CONSTRAINT UQ_CRM_PERSONS_1 UNIQUE (guid)';
    END IF;
END;
/

DECLARE
    v_exists NUMBER;
BEGIN
    -- Check if unique constraint on these columns already exists
    SELECT COUNT(*) INTO v_exists FROM all_constraints ac
    WHERE ac.owner = 'ODBVUE'
      AND ac.table_name = 'CRM_PERSONS'
      AND ac.constraint_type IN ('U', 'P')
      AND (SELECT LISTAGG(acc.column_name, ',') WITHIN GROUP (ORDER BY acc.position)
           FROM all_cons_columns acc WHERE acc.owner = ac.owner AND acc.constraint_name = ac.constraint_name) = 'GUID';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ODBVUE.CRM_PERSONS ADD CONSTRAINT UQ_CRM_PERSONS_2 UNIQUE (GUID)';
    END IF;
END;
/

DECLARE
    v_exists NUMBER;
BEGIN
    -- Check if unique constraint on these columns already exists
    SELECT COUNT(*) INTO v_exists FROM all_constraints ac
    WHERE ac.owner = 'ODBVUE'
      AND ac.table_name = 'APP_USERS'
      AND ac.constraint_type IN ('U', 'P')
      AND (SELECT LISTAGG(acc.column_name, ',') WITHIN GROUP (ORDER BY acc.position)
           FROM all_cons_columns acc WHERE acc.owner = ac.owner AND acc.constraint_name = ac.constraint_name) = 'UUID';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ODBVUE.APP_USERS ADD CONSTRAINT UQ_APP_USERS_3 UNIQUE (UUID)';
    END IF;
END;
/

DECLARE
    v_exists NUMBER;
BEGIN
    -- Check if unique constraint on these columns already exists
    SELECT COUNT(*) INTO v_exists FROM all_constraints ac
    WHERE ac.owner = 'ODBVUE'
      AND ac.table_name = 'APP_USERS'
      AND ac.constraint_type IN ('U', 'P')
      AND (SELECT LISTAGG(acc.column_name, ',') WITHIN GROUP (ORDER BY acc.position)
           FROM all_cons_columns acc WHERE acc.owner = ac.owner AND acc.constraint_name = ac.constraint_name) = 'USERNAME';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ODBVUE.APP_USERS ADD CONSTRAINT UQ_APP_USERS_4 UNIQUE (USERNAME)';
    END IF;
END;
/

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM all_indexes WHERE owner = 'ODBVUE' AND index_name = 'IDX_CRM_PERSONS_1';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX ODBVUE.IDX_CRM_PERSONS_1 ON ODBVUE.CRM_PERSONS (TYPE, STATUS)';
    END IF;
END;
/

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM all_indexes WHERE owner = 'ODBVUE' AND index_name = 'IDX_CRM_PERSONS_2';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX ODBVUE.IDX_CRM_PERSONS_2 ON ODBVUE.CRM_PERSONS (FIRST_NAME, LAST_NAME)';
    END IF;
END;
/
