import { Command } from 'commander';
import {
  logger,
  rootDir,
  path,
  existsSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
  readdirSync,
} from '../utils.js';

// ============================================================================
// Types
// ============================================================================

type ColumnInfo = {
  name: string;
  description?: string;
  type: string;
  default: string | null;
  required: boolean;
  identity: boolean;
};

type TableInfo = {
  name: string;
  description?: string;
  columns: ColumnInfo[];
  primary_key: string[];
  unique?: string[][];
  indexes?: string[][] | null;
  checks?: Array<{
    column: string;
    values: string[];
  }> | null;
  foreignKeys?: Array<{
    name: string;
    column: string;
    referenceTable: string;
    referenceColumn: string;
  }> | null;
};

type UpsertInfo = {
  table: string;
  key: string | string[];
  rows: Record<string, unknown>[];
};

type MethodParamInfo = {
  name: string;
  direction: 'IN' | 'OUT' | 'IN OUT';
  type: string;
  description?: string;
};

type MethodInfo = {
  name: string;
  type: 'PROCEDURE' | 'FUNCTION';
  returnType?: string;
  params?: MethodParamInfo[];
  body?: string;
  description?: string;
  authid?: string;
};

type ServiceInfo = {
  name: string;
  editionable?: boolean;
  authid?: string;
  methods?: MethodInfo[];
};

type SchemaJson = {
  schema: string;
  exported: string;
  tables: TableInfo[];
  upserts?: UpsertInfo[];
  services?: ServiceInfo[];
};

// ============================================================================
// SQL Generation Utilities
// ============================================================================

/**
 * Escape single quotes for use inside EXECUTE IMMEDIATE
 */
function escapeForExecuteImmediate(str: string): string {
  return str.replace(/'/g, "''");
}

/**
 * Generate idempotent CREATE TABLE with schema prefix
 */
function generateTableSql(schemaName: string, table: TableInfo): string {
  const fullTableName = `${schemaName}.${table.name}`;
  const lines: string[] = [];

  // Build column definitions (with escaped quotes for EXECUTE IMMEDIATE)
  const columnDefs: string[] = [];
  for (const col of table.columns) {
    let colDef = `  ${col.name} ${col.type}`;
    if (col.default) {
      const isStringType = /^(CHAR|VARCHAR2|CLOB)/i.test(col.type);
      const defaultValue = col.default.trim();
      const needsQuotes =
        isStringType && !defaultValue.includes('(') && !defaultValue.startsWith("'");
      if (needsQuotes) {
        // Inside EXECUTE IMMEDIATE: 'A' becomes ''A''
        colDef += ` DEFAULT ''${defaultValue}''`;
      } else {
        // Escape any existing quotes in the default value
        colDef += ` DEFAULT ${escapeForExecuteImmediate(defaultValue)}`;
      }
    }
    if (col.required) {
      colDef += ' NOT NULL';
    }
    if (col.identity) {
      colDef += ' GENERATED BY DEFAULT AS IDENTITY';
    }
    columnDefs.push(colDef);
  }

  // Add primary key constraint inline
  if (table.primary_key && table.primary_key.length > 0) {
    const pkName = `pk_${table.name}`.toLowerCase();
    columnDefs.push(
      `  CONSTRAINT ${pkName} PRIMARY KEY (${table.primary_key.join(', ')})`
    );
  }

  // Idempotent CREATE TABLE using exception handler
  lines.push(`-- Table: ${table.name}`);
  lines.push(`DECLARE`);
  lines.push(`  v_exists NUMBER;`);
  lines.push(`BEGIN`);
  lines.push(`  SELECT COUNT(*) INTO v_exists FROM all_tables WHERE owner = '${schemaName}' AND table_name = '${table.name}';`);
  lines.push(`  IF v_exists = 0 THEN`);
  lines.push(`    EXECUTE IMMEDIATE '`);
  lines.push(`CREATE TABLE ${fullTableName} (`);
  lines.push(columnDefs.join(',\n'));
  lines.push(`)';`);
  lines.push(`    DBMS_OUTPUT.PUT_LINE('Created table ${fullTableName}');`);
  lines.push(`  ELSE`);
  lines.push(`    DBMS_OUTPUT.PUT_LINE('Table ${fullTableName} already exists');`);
  lines.push(`  END IF;`);
  lines.push(`END;`);
  lines.push(`/`);
  lines.push('');

  // Table comment
  if (table.description) {
    lines.push(`COMMENT ON TABLE ${fullTableName} IS '${table.description.replace(/'/g, "''")}';`);
    lines.push('');
  }

  // Column comments
  for (const col of table.columns) {
    if (col.description) {
      lines.push(
        `COMMENT ON COLUMN ${fullTableName}.${col.name} IS '${col.description.replace(/'/g, "''")}';`
      );
    }
  }
  if (table.columns.some((c) => c.description)) {
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Generate idempotent constraint SQL
 */
function generateConstraintSql(
  schemaName: string,
  tableName: string,
  constraintName: string,
  constraintType: 'UNIQUE' | 'CHECK' | 'FOREIGN KEY',
  constraintDef: string
): string {
  const fullTableName = `${schemaName}.${tableName}`;
  const lines: string[] = [];

  lines.push(`-- Constraint: ${constraintName}`);
  lines.push(`DECLARE`);
  lines.push(`  v_exists NUMBER;`);
  lines.push(`BEGIN`);
  lines.push(`  SELECT COUNT(*) INTO v_exists FROM all_constraints WHERE owner = '${schemaName}' AND constraint_name = '${constraintName.toUpperCase()}';`);
  lines.push(`  IF v_exists = 0 THEN`);
  lines.push(`    EXECUTE IMMEDIATE 'ALTER TABLE ${fullTableName} ADD CONSTRAINT ${constraintName} ${constraintDef}';`);
  lines.push(`    DBMS_OUTPUT.PUT_LINE('Created constraint ${constraintName}');`);
  lines.push(`  ELSE`);
  lines.push(`    DBMS_OUTPUT.PUT_LINE('Constraint ${constraintName} already exists');`);
  lines.push(`  END IF;`);
  lines.push(`END;`);
  lines.push(`/`);
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate idempotent index SQL
 */
function generateIndexSql(
  schemaName: string,
  tableName: string,
  indexName: string,
  columns: string[]
): string {
  const fullTableName = `${schemaName}.${tableName}`;
  const fullIndexName = `${schemaName}.${indexName}`;
  const lines: string[] = [];

  lines.push(`-- Index: ${indexName}`);
  lines.push(`DECLARE`);
  lines.push(`  v_exists NUMBER;`);
  lines.push(`BEGIN`);
  lines.push(`  SELECT COUNT(*) INTO v_exists FROM all_indexes WHERE owner = '${schemaName}' AND index_name = '${indexName.toUpperCase()}';`);
  lines.push(`  IF v_exists = 0 THEN`);
  lines.push(`    EXECUTE IMMEDIATE 'CREATE INDEX ${fullIndexName} ON ${fullTableName} (${columns.join(', ')})';`);
  lines.push(`    DBMS_OUTPUT.PUT_LINE('Created index ${indexName}');`);
  lines.push(`  ELSE`);
  lines.push(`    DBMS_OUTPUT.PUT_LINE('Index ${indexName} already exists');`);
  lines.push(`  END IF;`);
  lines.push(`END;`);
  lines.push(`/`);
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate all constraints for a table
 */
function generateTableConstraintsSql(schemaName: string, table: TableInfo): string {
  const lines: string[] = [];

  // Unique constraints
  if (table.unique) {
    for (const cols of table.unique) {
      const ukName = `uk_${table.name}_${cols.join('_')}`.toLowerCase();
      lines.push(
        generateConstraintSql(
          schemaName,
          table.name,
          ukName,
          'UNIQUE',
          `UNIQUE (${cols.join(', ')})`
        )
      );
    }
  }

  // Check constraints
  if (table.checks) {
    for (const chk of table.checks) {
      const ckName = `ck_${table.name}_${chk.column}`.toLowerCase();
      const values = chk.values.map((v) => `''${v}''`).join(', ');
      lines.push(
        generateConstraintSql(
          schemaName,
          table.name,
          ckName,
          'CHECK',
          `CHECK (${chk.column} IN (${values}))`
        )
      );
    }
  }

  // Foreign key constraints
  if (table.foreignKeys) {
    for (const fk of table.foreignKeys) {
      const fkName = fk.name || `fk_${table.name}_${fk.column}`.toLowerCase();
      lines.push(
        generateConstraintSql(
          schemaName,
          table.name,
          fkName,
          'FOREIGN KEY',
          `FOREIGN KEY (${fk.column}) REFERENCES ${schemaName}.${fk.referenceTable}(${fk.referenceColumn})`
        )
      );
    }
  }

  return lines.join('\n');
}

/**
 * Generate all indexes for a table
 */
function generateTableIndexesSql(schemaName: string, table: TableInfo): string {
  const lines: string[] = [];

  if (table.indexes) {
    for (const cols of table.indexes) {
      const idxName = `idx_${table.name}_${cols.join('_')}`.toLowerCase();
      lines.push(generateIndexSql(schemaName, table.name, idxName, cols));
    }
  }

  return lines.join('\n');
}

/**
 * Generate package specification SQL
 */
function generatePackageSpecSql(schemaName: string, service: ServiceInfo): string {
  const lines: string[] = [];
  const fullPkgName = `${schemaName}.${service.name}`;
  const editionable = service.editionable !== false ? 'EDITIONABLE ' : '';
  const authid = service.authid || 'DEFINER';

  lines.push(`-- Package Specification: ${service.name}`);
  lines.push(`CREATE OR REPLACE ${editionable}PACKAGE ${fullPkgName}`);
  lines.push(`  AUTHID ${authid}`);
  lines.push(`AS`);
  lines.push('');

  if (service.methods) {
    for (const method of service.methods) {
      if (method.description) {
        lines.push(`  -- ${method.description}`);
      }

      if (method.type === 'FUNCTION') {
        const params = method.params
          ? method.params
              .map((p) => `${p.name} ${p.direction !== 'IN' ? p.direction + ' ' : ''}${p.type}`)
              .join(', ')
          : '';
        lines.push(
          `  FUNCTION ${method.name}${params ? `(${params})` : ''} RETURN ${method.returnType || 'VARCHAR2'};`
        );
      } else {
        const params = method.params
          ? method.params
              .map((p) => `${p.name} ${p.direction !== 'IN' ? p.direction + ' ' : ''}${p.type}`)
              .join(', ')
          : '';
        lines.push(`  PROCEDURE ${method.name}${params ? `(${params})` : ''};`);
      }
      lines.push('');
    }
  }

  lines.push(`END ${service.name};`);
  lines.push(`/`);
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate package body SQL
 */
function generatePackageBodySql(schemaName: string, service: ServiceInfo): string {
  const lines: string[] = [];
  const fullPkgName = `${schemaName}.${service.name}`;
  const editionable = service.editionable !== false ? 'EDITIONABLE ' : '';

  lines.push(`-- Package Body: ${service.name}`);
  lines.push(`CREATE OR REPLACE ${editionable}PACKAGE BODY ${fullPkgName}`);
  lines.push(`AS`);
  lines.push('');

  if (service.methods) {
    for (const method of service.methods) {
      if (method.type === 'FUNCTION') {
        const params = method.params
          ? method.params
              .map((p) => `${p.name} ${p.direction !== 'IN' ? p.direction + ' ' : ''}${p.type}`)
              .join(', ')
          : '';
        lines.push(
          `  FUNCTION ${method.name}${params ? `(${params})` : ''} RETURN ${method.returnType || 'VARCHAR2'}`
        );
        lines.push(`  IS`);
        lines.push(`  BEGIN`);
        if (method.body) {
          lines.push(`    ${method.body}`);
        } else {
          lines.push(`    RETURN NULL; -- TODO: Implement`);
        }
        lines.push(`  END ${method.name};`);
      } else {
        const params = method.params
          ? method.params
              .map((p) => `${p.name} ${p.direction !== 'IN' ? p.direction + ' ' : ''}${p.type}`)
              .join(', ')
          : '';
        lines.push(`  PROCEDURE ${method.name}${params ? `(${params})` : ''}`);
        lines.push(`  IS`);
        lines.push(`  BEGIN`);
        if (method.body) {
          lines.push(`    ${method.body}`);
        } else {
          lines.push(`    NULL; -- TODO: Implement`);
        }
        lines.push(`  END ${method.name};`);
      }
      lines.push('');
    }
  }

  lines.push(`END ${service.name};`);
  lines.push(`/`);
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate upsert (merge) SQL
 */
function generateUpsertSql(schemaName: string, upsert: UpsertInfo): string {
  const lines: string[] = [];
  const fullTableName = `${schemaName}.${upsert.table}`;
  const keys = Array.isArray(upsert.key) ? upsert.key : [upsert.key];

  for (const row of upsert.rows) {
    const columns = Object.keys(row);
    const nonKeyColumns = columns.filter((c) => !keys.includes(c.toUpperCase()));

    lines.push(`MERGE INTO ${fullTableName} t`);
    lines.push(`USING (`);
    lines.push(`  SELECT`);
    const selectParts = columns.map((col) => {
      const val = row[col];
      if (val === null) return `    NULL AS ${col}`;
      if (typeof val === 'string') return `    '${val.replace(/'/g, "''")}' AS ${col}`;
      return `    ${val} AS ${col}`;
    });
    lines.push(selectParts.join(',\n'));
    lines.push(`  FROM dual`);
    lines.push(`) s`);
    lines.push(`ON (${keys.map((k) => `t.${k} = s.${k}`).join(' AND ')})`);

    if (nonKeyColumns.length > 0) {
      lines.push(`WHEN MATCHED THEN`);
      lines.push(`  UPDATE SET`);
      lines.push(`    ${nonKeyColumns.map((c) => `t.${c} = s.${c}`).join(',\n    ')}`);
    }

    lines.push(`WHEN NOT MATCHED THEN`);
    lines.push(`  INSERT (${columns.join(', ')})`);
    lines.push(`  VALUES (${columns.map((c) => `s.${c}`).join(', ')});`);
    lines.push('');
  }

  return lines.join('\n');
}

// ============================================================================
// Main Import Function
// ============================================================================

async function importSchema(schemaDir: string, outputDir: string): Promise<void> {
  // Find all JSON files in schema directory
  const schemaPath = path.isAbsolute(schemaDir)
    ? schemaDir
    : path.resolve(process.cwd(), schemaDir);

  if (!existsSync(schemaPath)) {
    throw new Error(`Schema directory not found: ${schemaPath}`);
  }

  const outputPath = path.isAbsolute(outputDir)
    ? outputDir
    : path.resolve(process.cwd(), outputDir);

  // Ensure output directories exist
  mkdirSync(path.join(outputPath, 'scripts', 'before'), { recursive: true });
  mkdirSync(path.join(outputPath, 'tables'), { recursive: true });
  mkdirSync(path.join(outputPath, 'constraints'), { recursive: true });
  mkdirSync(path.join(outputPath, 'indexes'), { recursive: true });
  mkdirSync(path.join(outputPath, 'comments'), { recursive: true });
  mkdirSync(path.join(outputPath, 'packages'), { recursive: true });
  mkdirSync(path.join(outputPath, 'scripts', 'after'), { recursive: true });

  // Find JSON files
  const jsonFiles = readdirSync(schemaPath).filter((f) => f.endsWith('.json'));

  if (jsonFiles.length === 0) {
    logger.warn(`No JSON files found in ${schemaPath}`);
    return;
  }

  const masterScript: string[] = [
    '-- Auto-generated migration script',
    `-- Generated: ${new Date().toISOString()}`,
    '',
    '-- Enable DBMS_OUTPUT',
    'SET SERVEROUTPUT ON',
    '',
  ];

  let tableCount = 0;
  let constraintCount = 0;
  let indexCount = 0;
  let packageCount = 0;
  let upsertCount = 0;

  for (const jsonFile of jsonFiles) {
    const jsonPath = path.join(schemaPath, jsonFile);
    const content = readFileSync(jsonPath, 'utf-8');
    const schema: SchemaJson = JSON.parse(content);
    const schemaName = schema.schema.toUpperCase();

    logger.info(`Processing schema: ${schemaName} from ${jsonFile}`);

    // 1. Tables
    if (schema.tables && schema.tables.length > 0) {
      masterScript.push(`-- ============================================================================`);
      masterScript.push(`-- TABLES`);
      masterScript.push(`-- ============================================================================`);
      masterScript.push('');

      for (const table of schema.tables) {
        const tableSql = generateTableSql(schemaName, table);
        const tableFileName = `${table.name.toLowerCase()}.sql`;
        writeFileSync(path.join(outputPath, 'tables', tableFileName), tableSql);
        masterScript.push(`-- Table: ${table.name}`);
        masterScript.push(`@@tables/${tableFileName}`);
        masterScript.push('');
        tableCount++;
      }
    }

    // 2. Constraints
    if (schema.tables && schema.tables.some((t) => t.unique || t.checks || t.foreignKeys)) {
      masterScript.push(`-- ============================================================================`);
      masterScript.push(`-- CONSTRAINTS`);
      masterScript.push(`-- ============================================================================`);
      masterScript.push('');

      for (const table of schema.tables) {
        const constraintsSql = generateTableConstraintsSql(schemaName, table);
        if (constraintsSql.trim()) {
          const constraintFileName = `${table.name.toLowerCase()}_constraints.sql`;
          writeFileSync(path.join(outputPath, 'constraints', constraintFileName), constraintsSql);
          masterScript.push(`-- Constraints for: ${table.name}`);
          masterScript.push(`@@constraints/${constraintFileName}`);
          masterScript.push('');
          constraintCount++;
        }
      }
    }

    // 3. Indexes
    if (schema.tables && schema.tables.some((t) => t.indexes && t.indexes.length > 0)) {
      masterScript.push(`-- ============================================================================`);
      masterScript.push(`-- INDEXES`);
      masterScript.push(`-- ============================================================================`);
      masterScript.push('');

      for (const table of schema.tables) {
        const indexesSql = generateTableIndexesSql(schemaName, table);
        if (indexesSql.trim()) {
          const indexFileName = `${table.name.toLowerCase()}_indexes.sql`;
          writeFileSync(path.join(outputPath, 'indexes', indexFileName), indexesSql);
          masterScript.push(`-- Indexes for: ${table.name}`);
          masterScript.push(`@@indexes/${indexFileName}`);
          masterScript.push('');
          indexCount++;
        }
      }
    }

    // 4. Packages (Services)
    if (schema.services && schema.services.length > 0) {
      masterScript.push(`-- ============================================================================`);
      masterScript.push(`-- PACKAGES`);
      masterScript.push(`-- ============================================================================`);
      masterScript.push('');

      for (const service of schema.services) {
        // Package specification
        const specSql = generatePackageSpecSql(schemaName, service);
        const specFileName = `${service.name.toLowerCase()}_spec.sql`;
        writeFileSync(path.join(outputPath, 'packages', specFileName), specSql);
        masterScript.push(`-- Package spec: ${service.name}`);
        masterScript.push(`@@packages/${specFileName}`);
        masterScript.push('');

        // Package body
        const bodySql = generatePackageBodySql(schemaName, service);
        const bodyFileName = `${service.name.toLowerCase()}_body.sql`;
        writeFileSync(path.join(outputPath, 'packages', bodyFileName), bodySql);
        masterScript.push(`-- Package body: ${service.name}`);
        masterScript.push(`@@packages/${bodyFileName}`);
        masterScript.push('');

        packageCount++;
      }
    }

    // 5. Upserts (seed data)
    if (schema.upserts && schema.upserts.length > 0) {
      masterScript.push(`-- ============================================================================`);
      masterScript.push(`-- SEED DATA`);
      masterScript.push(`-- ============================================================================`);
      masterScript.push('');

      for (const upsert of schema.upserts) {
        const upsertSql = generateUpsertSql(schemaName, upsert);
        const upsertFileName = `${upsert.table.toLowerCase()}_data.sql`;
        writeFileSync(path.join(outputPath, 'scripts', 'after', upsertFileName), upsertSql);
        masterScript.push(`-- Data for: ${upsert.table}`);
        masterScript.push(`@@scripts/after/${upsertFileName}`);
        masterScript.push('');
        upsertCount++;
      }
    }
  }

  // Write master script
  const masterScriptPath = path.join(outputPath, 'next.sql');
  writeFileSync(masterScriptPath, masterScript.join('\n'));

  logger.success(`Generated migration scripts in ${path.relative(rootDir, outputPath)}/`);
  logger.info(`  Tables: ${tableCount}`);
  logger.info(`  Constraints: ${constraintCount}`);
  logger.info(`  Indexes: ${indexCount}`);
  logger.info(`  Packages: ${packageCount}`);
  logger.info(`  Upserts: ${upsertCount}`);
  logger.success(`Master script: ${path.relative(rootDir, masterScriptPath)}`);
}

// ============================================================================
// Command Registration
// ============================================================================

export const registerDbImportCommand = (program: Command) => {
  program
    .command('db-import')
    .alias('di')
    .description('Generate SQL migration scripts from JSON schema files')
    .argument('[schemaDir]', 'Directory containing JSON schema files', 'db/schema')
    .argument('[outputDir]', 'Output directory for SQL scripts', 'db/releases/next')
    .action(async (schemaDir: string, outputDir: string) => {
      try {
        await importSchema(schemaDir, outputDir);
      } catch (error) {
        logger.error(`Import failed: ${error instanceof Error ? error.message : String(error)}`);
        process.exit(1);
      }
    });
};
