-- Auto-generated master script
-- Generated: 2026-01-19T12:31:37.738Z

-- TABLES
-- Source: tables/

-- app_users.sql
CREATE TABLE APP_USERS (
  ID NUMBER(19,0) NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  UUID RAW(16) DEFAULT SYS_GUID() NOT NULL,
  USERNAME VARCHAR2(200 CHAR) NOT NULL,
  PASSWORD VARCHAR2(2000 CHAR) NOT NULL,
  FULLNAME VARCHAR2(200 CHAR) NOT NULL,
  STATUS CHAR(1 CHAR) DEFAULT 'A' NOT NULL,
  CREATED TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  ATTEMPTS NUMBER(19,0) DEFAULT 0 NOT NULL,
  ACCESSED TIMESTAMP(6),
  ATTEMPTED TIMESTAMP(6),
  CONSTRAINT pk_app_users PRIMARY KEY (ID)
);

-- CONSTRAINTS
-- Source: constraints/

-- uk_app_users_username.sql
ALTER TABLE APP_USERS ADD CONSTRAINT uk_app_users_username UNIQUE (USERNAME);

-- ck_app_users_status.sql
ALTER TABLE APP_USERS ADD CONSTRAINT ck_app_users_status CHECK (STATUS IN ('A', 'D', 'N'));

-- INDEXES
-- Source: indexes/

-- idx_app_users_status.sql
CREATE INDEX idx_app_users_status ON APP_USERS (STATUS);

-- idx_app_users_created.sql
CREATE INDEX idx_app_users_created ON APP_USERS (CREATED);

-- COMMENTS
-- Source: comments/

-- comments_app_users.sql
COMMENT ON TABLE APP_USERS IS 'Table for storing and processing user data';
COMMENT ON COLUMN APP_USERS.ID IS 'Primary key';
COMMENT ON COLUMN APP_USERS.UUID IS 'Unique user identifier';
COMMENT ON COLUMN APP_USERS.USERNAME IS 'Username';
COMMENT ON COLUMN APP_USERS.PASSWORD IS 'Password';
COMMENT ON COLUMN APP_USERS.FULLNAME IS 'Full name';
COMMENT ON COLUMN APP_USERS.STATUS IS 'Status (A - active; D - disabled; N - uNverified)';
COMMENT ON COLUMN APP_USERS.CREATED IS 'Date and time when user was created';
COMMENT ON COLUMN APP_USERS.ATTEMPTS IS 'Number of authentication attempts';
COMMENT ON COLUMN APP_USERS.ACCESSED IS 'Date and time when user performed last successful login';
COMMENT ON COLUMN APP_USERS.ATTEMPTED IS 'Timestamp of the last login attempt';
