DEFINE ODBVUE_PWD = '&1'

SET SERVEROUTPUT ON
DECLARE
  v_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_exists FROM dba_users WHERE username = 'ODBVUE';
  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE USER ODBVUE IDENTIFIED BY "'||REPLACE('&&ODBVUE_PWD','"', '""')||'"
      DEFAULT TABLESPACE DATA
      TEMPORARY TABLESPACE TEMP
      QUOTA UNLIMITED ON DATA';
  ELSE
    EXECUTE IMMEDIATE 'ALTER USER ODBVUE IDENTIFIED BY "'||REPLACE('&&ODBVUE_PWD','"', '""')||'"';
    EXECUTE IMMEDIATE 'ALTER USER ODBVUE ACCOUNT UNLOCK';
    EXECUTE IMMEDIATE 'ALTER USER ODBVUE QUOTA UNLIMITED ON DATA';
  END IF;

  FOR stmt IN (
    SELECT
      'GRANT CREATE SESSION TO ODBVUE' AS s FROM dual UNION ALL
    SELECT 'GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, CREATE TYPE TO ODBVUE' FROM dual UNION ALL
    SELECT 'GRANT CREATE SYNONYM TO ODBVUE' FROM dual
  )
  LOOP
    EXECUTE IMMEDIATE stmt.s;
  END LOOP;

  DBMS_OUTPUT.PUT_LINE('User ODBVUE ensured with required privileges.');
END;
/
