-- Auto-generated master script
-- Generated: 2026-01-19T12:59:23.464Z

-- TABLES
-- Source: tables/

-- app_users.sql
-- Table: APP_USERS
DECLARE
  v_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_exists FROM all_tables WHERE owner = 'ODBVUE' AND table_name = 'APP_USERS';
  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE '
CREATE TABLE ODBVUE.APP_USERS (
  ID NUMBER(19,0) NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  UUID RAW(16) DEFAULT SYS_GUID() NOT NULL,
  USERNAME VARCHAR2(200 CHAR) NOT NULL,
  PASSWORD VARCHAR2(2000 CHAR) NOT NULL,
  FULLNAME VARCHAR2(200 CHAR) NOT NULL,
  STATUS CHAR(1 CHAR) DEFAULT ''A'' NOT NULL,
  CREATED TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  ATTEMPTS NUMBER(19,0) DEFAULT 0 NOT NULL,
  ACCESSED TIMESTAMP(6),
  ATTEMPTED TIMESTAMP(6),
  CONSTRAINT pk_app_users PRIMARY KEY (ID)
)';
    DBMS_OUTPUT.PUT_LINE('Created table ODBVUE.APP_USERS');
  ELSE
    DBMS_OUTPUT.PUT_LINE('Table ODBVUE.APP_USERS already exists');
  END IF;
END;
/

-- CONSTRAINTS
-- Source: constraints/

-- uk_app_users_username.sql
-- Constraint: uk_app_users_username
DECLARE
  v_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_exists FROM all_constraints WHERE owner = 'ODBVUE' AND constraint_name = 'UK_APP_USERS_USERNAME';
  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ODBVUE.APP_USERS ADD CONSTRAINT uk_app_users_username UNIQUE (USERNAME)';
    DBMS_OUTPUT.PUT_LINE('Created constraint uk_app_users_username');
  ELSE
    DBMS_OUTPUT.PUT_LINE('Constraint uk_app_users_username already exists');
  END IF;
END;
/

-- ck_app_users_status.sql
-- Constraint: ck_app_users_status
DECLARE
  v_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_exists FROM all_constraints WHERE owner = 'ODBVUE' AND constraint_name = 'CK_APP_USERS_STATUS';
  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ODBVUE.APP_USERS ADD CONSTRAINT ck_app_users_status CHECK (STATUS IN (''A'', ''D'', ''N''))';
    DBMS_OUTPUT.PUT_LINE('Created constraint ck_app_users_status');
  ELSE
    DBMS_OUTPUT.PUT_LINE('Constraint ck_app_users_status already exists');
  END IF;
END;
/

-- INDEXES
-- Source: indexes/

-- idx_app_users_status.sql
-- Index: idx_app_users_status
DECLARE
  v_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_exists FROM all_indexes WHERE owner = 'ODBVUE' AND index_name = 'IDX_APP_USERS_STATUS';
  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ODBVUE.idx_app_users_status ON ODBVUE.APP_USERS (STATUS)';
    DBMS_OUTPUT.PUT_LINE('Created index idx_app_users_status');
  ELSE
    DBMS_OUTPUT.PUT_LINE('Index idx_app_users_status already exists');
  END IF;
END;
/

-- idx_app_users_created.sql
-- Index: idx_app_users_created
DECLARE
  v_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_exists FROM all_indexes WHERE owner = 'ODBVUE' AND index_name = 'IDX_APP_USERS_CREATED';
  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ODBVUE.idx_app_users_created ON ODBVUE.APP_USERS (CREATED)';
    DBMS_OUTPUT.PUT_LINE('Created index idx_app_users_created');
  ELSE
    DBMS_OUTPUT.PUT_LINE('Index idx_app_users_created already exists');
  END IF;
END;
/

-- COMMENTS
-- Source: comments/

-- comments_app_users.sql
COMMENT ON TABLE ODBVUE.APP_USERS IS 'Table for storing and processing user data';
COMMENT ON COLUMN ODBVUE.APP_USERS.ID IS 'Primary key';
COMMENT ON COLUMN ODBVUE.APP_USERS.UUID IS 'Unique user identifier';
COMMENT ON COLUMN ODBVUE.APP_USERS.USERNAME IS 'Username';
COMMENT ON COLUMN ODBVUE.APP_USERS.PASSWORD IS 'Password';
COMMENT ON COLUMN ODBVUE.APP_USERS.FULLNAME IS 'Full name';
COMMENT ON COLUMN ODBVUE.APP_USERS.STATUS IS 'Status (A - active; D - disabled; N - uNverified)';
COMMENT ON COLUMN ODBVUE.APP_USERS.CREATED IS 'Date and time when user was created';
COMMENT ON COLUMN ODBVUE.APP_USERS.ATTEMPTS IS 'Number of authentication attempts';
COMMENT ON COLUMN ODBVUE.APP_USERS.ACCESSED IS 'Date and time when user performed last successful login';
COMMENT ON COLUMN ODBVUE.APP_USERS.ATTEMPTED IS 'Timestamp of the last login attempt';
