platforms:
  - platform: local-podman
    spec:
      name: odbvue-dev
services:
  - name: odbvue-adb
    kind: oracle-adb
    platform: local-podman
    spec:
      listenerPort: '1522'
      ordsPort: '8443'
