/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/': RouteRecordInfo<
      '/sandbox/',
      '/sandbox',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/sandbox-chart': RouteRecordInfo<
      '/sandbox/sandbox-chart',
      '/sandbox/sandbox-chart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/sandbox-editor': RouteRecordInfo<
      '/sandbox/sandbox-editor',
      '/sandbox/sandbox-editor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/sandbox-form': RouteRecordInfo<
      '/sandbox/sandbox-form',
      '/sandbox/sandbox-form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/sandbox-map': RouteRecordInfo<
      '/sandbox/sandbox-map',
      '/sandbox/sandbox-map',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/sandbox-media': RouteRecordInfo<
      '/sandbox/sandbox-media',
      '/sandbox/sandbox-media',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/sandbox-pad': RouteRecordInfo<
      '/sandbox/sandbox-pad',
      '/sandbox/sandbox-pad',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/sandbox-share': RouteRecordInfo<
      '/sandbox/sandbox-share',
      '/sandbox/sandbox-share',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/sandbox-table': RouteRecordInfo<
      '/sandbox/sandbox-table',
      '/sandbox/sandbox-table',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/about.md': {
      routes:
        | '/about'
      views:
        | never
    }
    'src/pages/sandbox/index.vue': {
      routes:
        | '/sandbox/'
      views:
        | never
    }
    'src/pages/sandbox/sandbox-chart.vue': {
      routes:
        | '/sandbox/sandbox-chart'
      views:
        | never
    }
    'src/pages/sandbox/sandbox-editor.vue': {
      routes:
        | '/sandbox/sandbox-editor'
      views:
        | never
    }
    'src/pages/sandbox/sandbox-form.vue': {
      routes:
        | '/sandbox/sandbox-form'
      views:
        | never
    }
    'src/pages/sandbox/sandbox-map.vue': {
      routes:
        | '/sandbox/sandbox-map'
      views:
        | never
    }
    'src/pages/sandbox/sandbox-media.vue': {
      routes:
        | '/sandbox/sandbox-media'
      views:
        | never
    }
    'src/pages/sandbox/sandbox-pad.vue': {
      routes:
        | '/sandbox/sandbox-pad'
      views:
        | never
    }
    'src/pages/sandbox/sandbox-share.vue': {
      routes:
        | '/sandbox/sandbox-share'
      views:
        | never
    }
    'src/pages/sandbox/sandbox-table.vue': {
      routes:
        | '/sandbox/sandbox-table'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
