/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/audit': RouteRecordInfo<
      '/admin/audit',
      '/admin/audit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/emails': RouteRecordInfo<
      '/admin/emails',
      '/admin/emails',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/jobs/': RouteRecordInfo<
      '/admin/jobs/',
      '/admin/jobs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/jobs/[name]': RouteRecordInfo<
      '/admin/jobs/[name]',
      '/admin/jobs/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/admin/roles/': RouteRecordInfo<
      '/admin/roles/',
      '/admin/roles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/roles/[role]': RouteRecordInfo<
      '/admin/roles/[role]',
      '/admin/roles/:role',
      { role: ParamValue<true> },
      { role: ParamValue<false> },
      | never
    >,
    '/admin/settings': RouteRecordInfo<
      '/admin/settings',
      '/admin/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/users/': RouteRecordInfo<
      '/admin/users/',
      '/admin/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/users/[uuid]': RouteRecordInfo<
      '/admin/users/[uuid]',
      '/admin/users/:uuid',
      { uuid: ParamValue<true> },
      { uuid: ParamValue<false> },
      | never
    >,
    '/confirm-email/[id]': RouteRecordInfo<
      '/confirm-email/[id]',
      '/confirm-email/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/crm/': RouteRecordInfo<
      '/crm/',
      '/crm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/recover-password': RouteRecordInfo<
      '/recover-password',
      '/recover-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reset-password/[token]': RouteRecordInfo<
      '/reset-password/[token]',
      '/reset-password/:token',
      { token: ParamValue<true> },
      { token: ParamValue<false> },
      | never
    >,
    '/rest': RouteRecordInfo<
      '/rest',
      '/rest',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/': RouteRecordInfo<
      '/sandbox/',
      '/sandbox',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/sandbox-chart': RouteRecordInfo<
      '/sandbox/sandbox-chart',
      '/sandbox/sandbox-chart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/sandbox-dialog': RouteRecordInfo<
      '/sandbox/sandbox-dialog',
      '/sandbox/sandbox-dialog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/sandbox-editor': RouteRecordInfo<
      '/sandbox/sandbox-editor',
      '/sandbox/sandbox-editor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/sandbox-form': RouteRecordInfo<
      '/sandbox/sandbox-form',
      '/sandbox/sandbox-form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/sandbox-map': RouteRecordInfo<
      '/sandbox/sandbox-map',
      '/sandbox/sandbox-map',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/sandbox-media': RouteRecordInfo<
      '/sandbox/sandbox-media',
      '/sandbox/sandbox-media',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/sandbox-pad': RouteRecordInfo<
      '/sandbox/sandbox-pad',
      '/sandbox/sandbox-pad',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/sandbox-share': RouteRecordInfo<
      '/sandbox/sandbox-share',
      '/sandbox/sandbox-share',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/sandbox-table': RouteRecordInfo<
      '/sandbox/sandbox-table',
      '/sandbox/sandbox-table',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sandbox/sandbox-view': RouteRecordInfo<
      '/sandbox/sandbox-view',
      '/sandbox/sandbox-view',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/signup': RouteRecordInfo<
      '/signup',
      '/signup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/travail/': RouteRecordInfo<
      '/travail/',
      '/travail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/travail/[num]': RouteRecordInfo<
      '/travail/[num]',
      '/travail/:num',
      { num: ParamValue<true> },
      { num: ParamValue<false> },
      | never
    >,
    '/travail/boards': RouteRecordInfo<
      '/travail/boards',
      '/travail/boards',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/about.md': {
      routes:
        | '/about'
      views:
        | never
    }
    'src/pages/admin/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
    }
    'src/pages/admin/audit.vue': {
      routes:
        | '/admin/audit'
      views:
        | never
    }
    'src/pages/admin/emails.vue': {
      routes:
        | '/admin/emails'
      views:
        | never
    }
    'src/pages/admin/jobs/index.vue': {
      routes:
        | '/admin/jobs/'
      views:
        | never
    }
    'src/pages/admin/jobs/[name].vue': {
      routes:
        | '/admin/jobs/[name]'
      views:
        | never
    }
    'src/pages/admin/roles/index.vue': {
      routes:
        | '/admin/roles/'
      views:
        | never
    }
    'src/pages/admin/roles/[role].vue': {
      routes:
        | '/admin/roles/[role]'
      views:
        | never
    }
    'src/pages/admin/settings.vue': {
      routes:
        | '/admin/settings'
      views:
        | never
    }
    'src/pages/admin/users/index.vue': {
      routes:
        | '/admin/users/'
      views:
        | never
    }
    'src/pages/admin/users/[uuid].vue': {
      routes:
        | '/admin/users/[uuid]'
      views:
        | never
    }
    'src/pages/confirm-email/[id].vue': {
      routes:
        | '/confirm-email/[id]'
      views:
        | never
    }
    'src/pages/crm/index.vue': {
      routes:
        | '/crm/'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/recover-password.vue': {
      routes:
        | '/recover-password'
      views:
        | never
    }
    'src/pages/reset-password/[token].vue': {
      routes:
        | '/reset-password/[token]'
      views:
        | never
    }
    'src/pages/rest.vue': {
      routes:
        | '/rest'
      views:
        | never
    }
    'src/pages/sandbox/index.vue': {
      routes:
        | '/sandbox/'
      views:
        | never
    }
    'src/pages/sandbox/sandbox-chart.vue': {
      routes:
        | '/sandbox/sandbox-chart'
      views:
        | never
    }
    'src/pages/sandbox/sandbox-dialog.vue': {
      routes:
        | '/sandbox/sandbox-dialog'
      views:
        | never
    }
    'src/pages/sandbox/sandbox-editor.vue': {
      routes:
        | '/sandbox/sandbox-editor'
      views:
        | never
    }
    'src/pages/sandbox/sandbox-form.vue': {
      routes:
        | '/sandbox/sandbox-form'
      views:
        | never
    }
    'src/pages/sandbox/sandbox-map.vue': {
      routes:
        | '/sandbox/sandbox-map'
      views:
        | never
    }
    'src/pages/sandbox/sandbox-media.vue': {
      routes:
        | '/sandbox/sandbox-media'
      views:
        | never
    }
    'src/pages/sandbox/sandbox-pad.vue': {
      routes:
        | '/sandbox/sandbox-pad'
      views:
        | never
    }
    'src/pages/sandbox/sandbox-share.vue': {
      routes:
        | '/sandbox/sandbox-share'
      views:
        | never
    }
    'src/pages/sandbox/sandbox-table.vue': {
      routes:
        | '/sandbox/sandbox-table'
      views:
        | never
    }
    'src/pages/sandbox/sandbox-view.vue': {
      routes:
        | '/sandbox/sandbox-view'
      views:
        | never
    }
    'src/pages/signup.vue': {
      routes:
        | '/signup'
      views:
        | never
    }
    'src/pages/travail/index.vue': {
      routes:
        | '/travail/'
      views:
        | never
    }
    'src/pages/travail/[num].vue': {
      routes:
        | '/travail/[num]'
      views:
        | never
    }
    'src/pages/travail/boards.vue': {
      routes:
        | '/travail/boards'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
