# Environment Definitions
# This file defines the available environments and their characteristics

environments:
  test:
    description: "Development and testing environment"
    profile_default: "DEFAULT"
    terraform_workspace: "test"
    auto_approve: true  # Can auto-approve terraform apply
    destroy_protection: false
    backup_required: false
    
  prod:
    description: "Production environment"
    profile_default: "DEFAULT"
    terraform_workspace: "prod"
    auto_approve: false  # Requires manual approval
    destroy_protection: true
    backup_required: true

# Profile mappings (can override per environment)
profiles:
  DEFAULT:
    description: "Default OCI profile"
    config_file: "~/.oci/config"
    
  PRODUCTION:
    description: "Production-specific OCI profile"
    config_file: "~/.oci/config"
    
# Global settings
global:
  default_region: "eu-frankfurt-1"
  terraform_version: "~> 1.0"
  oci_provider_version: "~> 5.0"
  
# Validation rules
validation:
  required_tags:
    - "Project"
    - "Environment" 
    - "CreatedBy"
  
  allowed_regions:
    - "eu-frankfurt-1"
    - "us-phoenix-1"
    - "us-ashburn-1"