name: Changesets
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          package_json_file: 'apps/package.json'
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: 'apps/pnpm-lock.yaml'
      - run: cd apps && pnpm install --frozen-lockfile
      - run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Verify changeset directory
        shell: bash
        run: |
          echo "Workspace contents:" && ls -la
          echo "apps contents:" && ls -la apps
          echo ".changeset contents:" && ls -la apps/.changeset
      - name: Apply version bump and push
        shell: bash
        run: |
          cd apps
          pnpm changeset version || true
          git add -A
          if git diff --cached --quiet; then
            echo "No version changes to commit."
            exit 0
          fi
          git commit -m "chore(release): version bump and changelog"
          # Push back to the same branch (typically main)
          git push origin "HEAD:${GITHUB_REF_NAME}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
